# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createpointmutation_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreatePointMutation(object):
    def setupUi(self, CreatePointMutation):
        CreatePointMutation.setObjectName("CreatePointMutation")
        CreatePointMutation.resize(285, 170)
        CreatePointMutation.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(CreatePointMutation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(CreatePointMutation)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.leOldResidue = QtWidgets.QLineEdit(CreatePointMutation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leOldResidue.sizePolicy().hasHeightForWidth())
        self.leOldResidue.setSizePolicy(sizePolicy)
        self.leOldResidue.setMinimumSize(QtCore.QSize(20, 0))
        self.leOldResidue.setMaxLength(1)
        self.leOldResidue.setObjectName("leOldResidue")
        self.horizontalLayout.addWidget(self.leOldResidue)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(CreatePointMutation)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.leNewResidue = QtWidgets.QLineEdit(CreatePointMutation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leNewResidue.sizePolicy().hasHeightForWidth())
        self.leNewResidue.setSizePolicy(sizePolicy)
        self.leNewResidue.setMinimumSize(QtCore.QSize(20, 0))
        self.leNewResidue.setMaxLength(1)
        self.leNewResidue.setObjectName("leNewResidue")
        self.horizontalLayout.addWidget(self.leNewResidue)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lbFormula = QtWidgets.QLabel(CreatePointMutation)
        self.lbFormula.setObjectName("lbFormula")
        self.gridLayout.addWidget(self.lbFormula, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(CreatePointMutation)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.lbMass = QtWidgets.QLabel(CreatePointMutation)
        self.lbMass.setObjectName("lbMass")
        self.gridLayout.addWidget(self.lbMass, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(CreatePointMutation)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lbMutation = QtWidgets.QLabel(CreatePointMutation)
        self.lbMutation.setObjectName("lbMutation")
        self.gridLayout.addWidget(self.lbMutation, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(CreatePointMutation)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.buttonBox = QtWidgets.QDialogButtonBox(CreatePointMutation)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CreatePointMutation)
        self.buttonBox.accepted.connect(CreatePointMutation.accept)
        self.buttonBox.rejected.connect(CreatePointMutation.reject)
        QtCore.QMetaObject.connectSlotsByName(CreatePointMutation)

    def retranslateUi(self, CreatePointMutation):
        _translate = QtCore.QCoreApplication.translate
        CreatePointMutation.setWindowTitle(_translate("CreatePointMutation", "Create point mutation"))
        self.label.setText(_translate("CreatePointMutation", "Mutate"))
        self.label_2.setText(_translate("CreatePointMutation", "to"))
        self.lbFormula.setText(_translate("CreatePointMutation", "C5 H4 O-1"))
        self.label_5.setText(_translate("CreatePointMutation", "Mass:"))
        self.lbMass.setText(_translate("CreatePointMutation", "48.0880 Da"))
        self.label_4.setText(_translate("CreatePointMutation", "Formula:"))
        self.lbMutation.setText(_translate("CreatePointMutation", "Ser to Val"))
        self.label_3.setText(_translate("CreatePointMutation", "Mutation:"))

