# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModFinder_UI.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ModFinder(object):
    def setupUi(self, ModFinder):
        ModFinder.setObjectName("ModFinder")
        ModFinder.resize(1356, 934)
        self.centralwidget = QtWidgets.QWidget(ModFinder)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.hlTop = QtWidgets.QHBoxLayout()
        self.hlTop.setSpacing(18)
        self.hlTop.setObjectName("hlTop")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(0, 6, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btLoadSequence = QtWidgets.QToolButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/mofi resource/images/Open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btLoadSequence.setIcon(icon)
        self.btLoadSequence.setIconSize(QtCore.QSize(24, 24))
        self.btLoadSequence.setAutoRaise(True)
        self.btLoadSequence.setObjectName("btLoadSequence")
        self.verticalLayout_11.addWidget(self.btLoadSequence)
        self.btSaveSequence = QtWidgets.QToolButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/mofi resource/images/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btSaveSequence.setIcon(icon1)
        self.btSaveSequence.setIconSize(QtCore.QSize(24, 24))
        self.btSaveSequence.setAutoRaise(True)
        self.btSaveSequence.setObjectName("btSaveSequence")
        self.verticalLayout_11.addWidget(self.btSaveSequence)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.btClearSequence = QtWidgets.QToolButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/mofi resource/images/Clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btClearSequence.setIcon(icon2)
        self.btClearSequence.setIconSize(QtCore.QSize(24, 24))
        self.btClearSequence.setAutoRaise(True)
        self.btClearSequence.setObjectName("btClearSequence")
        self.verticalLayout_11.addWidget(self.btClearSequence)
        self.btUpdateMass = QtWidgets.QToolButton(self.groupBox)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/mofi resource/images/UpdateMass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btUpdateMass.setIcon(icon3)
        self.btUpdateMass.setIconSize(QtCore.QSize(24, 24))
        self.btUpdateMass.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btUpdateMass.setAutoRaise(True)
        self.btUpdateMass.setObjectName("btUpdateMass")
        self.verticalLayout_11.addWidget(self.btUpdateMass)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.teSequence = QtWidgets.QTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teSequence.sizePolicy().hasHeightForWidth())
        self.teSequence.setSizePolicy(sizePolicy)
        self.teSequence.setMinimumSize(QtCore.QSize(350, 200))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.teSequence.setFont(font)
        self.teSequence.setObjectName("teSequence")
        self.horizontalLayout_3.addWidget(self.teSequence)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.sbDisulfides = QtWidgets.QSpinBox(self.centralwidget)
        self.sbDisulfides.setEnabled(False)
        self.sbDisulfides.setMinimumSize(QtCore.QSize(45, 25))
        self.sbDisulfides.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sbDisulfides.setMaximum(0)
        self.sbDisulfides.setObjectName("sbDisulfides")
        self.horizontalLayout_6.addWidget(self.sbDisulfides)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.chPngase = QtWidgets.QCheckBox(self.centralwidget)
        self.chPngase.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chPngase.sizePolicy().hasHeightForWidth())
        self.chPngase.setSizePolicy(sizePolicy)
        self.chPngase.setIconSize(QtCore.QSize(16, 16))
        self.chPngase.setChecked(False)
        self.chPngase.setObjectName("chPngase")
        self.horizontalLayout_6.addWidget(self.chPngase)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.cbMassSet = QtWidgets.QComboBox(self.centralwidget)
        self.cbMassSet.setMinimumSize(QtCore.QSize(0, 25))
        self.cbMassSet.setObjectName("cbMassSet")
        self.horizontalLayout_6.addWidget(self.cbMassSet)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.hlTop.addLayout(self.verticalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setContentsMargins(0, 6, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btLoadMonomers = QtWidgets.QToolButton(self.groupBox_2)
        self.btLoadMonomers.setIcon(icon)
        self.btLoadMonomers.setIconSize(QtCore.QSize(24, 24))
        self.btLoadMonomers.setAutoRaise(True)
        self.btLoadMonomers.setObjectName("btLoadMonomers")
        self.verticalLayout_7.addWidget(self.btLoadMonomers)
        self.btSaveMonomers = QtWidgets.QToolButton(self.groupBox_2)
        self.btSaveMonomers.setIcon(icon1)
        self.btSaveMonomers.setIconSize(QtCore.QSize(24, 24))
        self.btSaveMonomers.setAutoRaise(True)
        self.btSaveMonomers.setObjectName("btSaveMonomers")
        self.verticalLayout_7.addWidget(self.btSaveMonomers)
        self.btDefaultMonomers = QtWidgets.QToolButton(self.groupBox_2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/mofi resource/images/DefaultEntries.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btDefaultMonomers.setIcon(icon4)
        self.btDefaultMonomers.setIconSize(QtCore.QSize(24, 24))
        self.btDefaultMonomers.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btDefaultMonomers.setAutoRaise(True)
        self.btDefaultMonomers.setObjectName("btDefaultMonomers")
        self.verticalLayout_7.addWidget(self.btDefaultMonomers)
        self.btInsertRowAboveMonomers = QtWidgets.QToolButton(self.groupBox_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/mofi resource/images/InsertRowAbove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btInsertRowAboveMonomers.setIcon(icon5)
        self.btInsertRowAboveMonomers.setIconSize(QtCore.QSize(24, 24))
        self.btInsertRowAboveMonomers.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btInsertRowAboveMonomers.setAutoRaise(True)
        self.btInsertRowAboveMonomers.setObjectName("btInsertRowAboveMonomers")
        self.verticalLayout_7.addWidget(self.btInsertRowAboveMonomers)
        self.btInsertRowBelowMonomers = QtWidgets.QToolButton(self.groupBox_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/mofi resource/images/InsertRowBelow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btInsertRowBelowMonomers.setIcon(icon6)
        self.btInsertRowBelowMonomers.setIconSize(QtCore.QSize(24, 24))
        self.btInsertRowBelowMonomers.setAutoRaise(True)
        self.btInsertRowBelowMonomers.setObjectName("btInsertRowBelowMonomers")
        self.verticalLayout_7.addWidget(self.btInsertRowBelowMonomers)
        self.btDeleteRowMonomers = QtWidgets.QToolButton(self.groupBox_2)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/mofi resource/images/DeleteRow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btDeleteRowMonomers.setIcon(icon7)
        self.btDeleteRowMonomers.setIconSize(QtCore.QSize(24, 24))
        self.btDeleteRowMonomers.setAutoRaise(True)
        self.btDeleteRowMonomers.setObjectName("btDeleteRowMonomers")
        self.verticalLayout_7.addWidget(self.btDeleteRowMonomers)
        self.btClearMonomers = QtWidgets.QToolButton(self.groupBox_2)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/mofi resource/images/ClearTable.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btClearMonomers.setIcon(icon8)
        self.btClearMonomers.setIconSize(QtCore.QSize(24, 24))
        self.btClearMonomers.setAutoRaise(True)
        self.btClearMonomers.setObjectName("btClearMonomers")
        self.verticalLayout_7.addWidget(self.btClearMonomers)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.tbMonomers = QtWidgets.QTableWidget(self.groupBox_2)
        self.tbMonomers.setMinimumSize(QtCore.QSize(400, 0))
        self.tbMonomers.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tbMonomers.setColumnCount(5)
        self.tbMonomers.setObjectName("tbMonomers")
        self.tbMonomers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbMonomers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbMonomers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbMonomers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbMonomers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbMonomers.setHorizontalHeaderItem(4, item)
        self.tbMonomers.horizontalHeader().setDefaultSectionSize(60)
        self.horizontalLayout_4.addWidget(self.tbMonomers)
        self.hlTop.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setContentsMargins(0, 6, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btLoadPolymers = QtWidgets.QToolButton(self.groupBox_4)
        self.btLoadPolymers.setIcon(icon)
        self.btLoadPolymers.setIconSize(QtCore.QSize(24, 24))
        self.btLoadPolymers.setAutoRaise(True)
        self.btLoadPolymers.setObjectName("btLoadPolymers")
        self.verticalLayout_8.addWidget(self.btLoadPolymers)
        self.btSavePolymers = QtWidgets.QToolButton(self.groupBox_4)
        self.btSavePolymers.setIcon(icon1)
        self.btSavePolymers.setIconSize(QtCore.QSize(24, 24))
        self.btSavePolymers.setAutoRaise(True)
        self.btSavePolymers.setObjectName("btSavePolymers")
        self.verticalLayout_8.addWidget(self.btSavePolymers)
        self.btDefaultPolymers = QtWidgets.QToolButton(self.groupBox_4)
        self.btDefaultPolymers.setIcon(icon4)
        self.btDefaultPolymers.setIconSize(QtCore.QSize(24, 24))
        self.btDefaultPolymers.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btDefaultPolymers.setAutoRaise(True)
        self.btDefaultPolymers.setObjectName("btDefaultPolymers")
        self.verticalLayout_8.addWidget(self.btDefaultPolymers)
        self.btInsertRowAbovePolymers = QtWidgets.QToolButton(self.groupBox_4)
        self.btInsertRowAbovePolymers.setIcon(icon5)
        self.btInsertRowAbovePolymers.setIconSize(QtCore.QSize(24, 24))
        self.btInsertRowAbovePolymers.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.btInsertRowAbovePolymers.setAutoRaise(True)
        self.btInsertRowAbovePolymers.setObjectName("btInsertRowAbovePolymers")
        self.verticalLayout_8.addWidget(self.btInsertRowAbovePolymers)
        self.btInsertRowBelowPolymers = QtWidgets.QToolButton(self.groupBox_4)
        self.btInsertRowBelowPolymers.setIcon(icon6)
        self.btInsertRowBelowPolymers.setIconSize(QtCore.QSize(24, 24))
        self.btInsertRowBelowPolymers.setAutoRaise(True)
        self.btInsertRowBelowPolymers.setObjectName("btInsertRowBelowPolymers")
        self.verticalLayout_8.addWidget(self.btInsertRowBelowPolymers)
        self.btDeleteRowPolymers = QtWidgets.QToolButton(self.groupBox_4)
        self.btDeleteRowPolymers.setIcon(icon7)
        self.btDeleteRowPolymers.setIconSize(QtCore.QSize(24, 24))
        self.btDeleteRowPolymers.setAutoRaise(True)
        self.btDeleteRowPolymers.setObjectName("btDeleteRowPolymers")
        self.verticalLayout_8.addWidget(self.btDeleteRowPolymers)
        self.btClearPolymers = QtWidgets.QToolButton(self.groupBox_4)
        self.btClearPolymers.setIcon(icon8)
        self.btClearPolymers.setIconSize(QtCore.QSize(24, 24))
        self.btClearPolymers.setAutoRaise(True)
        self.btClearPolymers.setObjectName("btClearPolymers")
        self.verticalLayout_8.addWidget(self.btClearPolymers)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.tbPolymers = QtWidgets.QTableWidget(self.groupBox_4)
        self.tbPolymers.setMinimumSize(QtCore.QSize(400, 0))
        self.tbPolymers.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tbPolymers.setColumnCount(5)
        self.tbPolymers.setObjectName("tbPolymers")
        self.tbPolymers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbPolymers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbPolymers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbPolymers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbPolymers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbPolymers.setHorizontalHeaderItem(4, item)
        self.tbPolymers.horizontalHeader().setDefaultSectionSize(70)
        self.horizontalLayout_5.addWidget(self.tbPolymers)
        self.hlTop.addWidget(self.groupBox_4)
        self.verticalLayout_6.addLayout(self.hlTop)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.hlCenter = QtWidgets.QHBoxLayout()
        self.hlCenter.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hlCenter.setObjectName("hlCenter")
        self.spectrumView = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectrumView.sizePolicy().hasHeightForWidth())
        self.spectrumView.setSizePolicy(sizePolicy)
        self.spectrumView.setMinimumSize(QtCore.QSize(500, 0))
        self.spectrumView.setObjectName("spectrumView")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.spectrumView)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.vlSpectrumView = QtWidgets.QVBoxLayout()
        self.vlSpectrumView.setObjectName("vlSpectrumView")
        self.verticalLayout_10.addLayout(self.vlSpectrumView)
        self.hlCenter.addWidget(self.spectrumView)
        self.gbDeltaSeries = QtWidgets.QGroupBox(self.centralwidget)
        self.gbDeltaSeries.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbDeltaSeries.sizePolicy().hasHeightForWidth())
        self.gbDeltaSeries.setSizePolicy(sizePolicy)
        self.gbDeltaSeries.setMinimumSize(QtCore.QSize(159, 0))
        self.gbDeltaSeries.setObjectName("gbDeltaSeries")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gbDeltaSeries)
        self.gridLayout_9.setVerticalSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.chCombineDelta = QtWidgets.QCheckBox(self.gbDeltaSeries)
        self.chCombineDelta.setObjectName("chCombineDelta")
        self.horizontalLayout_13.addWidget(self.chCombineDelta)
        self.gridLayout_9.addLayout(self.horizontalLayout_13, 12, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gbDeltaSeries)
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sbDeltaTolerance1 = QtWidgets.QDoubleSpinBox(self.gbDeltaSeries)
        self.sbDeltaTolerance1.setMinimumSize(QtCore.QSize(75, 20))
        self.sbDeltaTolerance1.setMinimum(0.1)
        self.sbDeltaTolerance1.setSingleStep(0.1)
        self.sbDeltaTolerance1.setProperty("value", 5.0)
        self.sbDeltaTolerance1.setObjectName("sbDeltaTolerance1")
        self.horizontalLayout_7.addWidget(self.sbDeltaTolerance1)
        self.sbDeltaTolerance2 = QtWidgets.QDoubleSpinBox(self.gbDeltaSeries)
        self.sbDeltaTolerance2.setMinimumSize(QtCore.QSize(75, 20))
        self.sbDeltaTolerance2.setMinimum(0.1)
        self.sbDeltaTolerance2.setSingleStep(0.1)
        self.sbDeltaTolerance2.setProperty("value", 5.0)
        self.sbDeltaTolerance2.setObjectName("sbDeltaTolerance2")
        self.horizontalLayout_7.addWidget(self.sbDeltaTolerance2)
        self.gridLayout_9.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gbDeltaSeries)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 2, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.sbDeltaValue1 = QtWidgets.QDoubleSpinBox(self.gbDeltaSeries)
        self.sbDeltaValue1.setEnabled(False)
        self.sbDeltaValue1.setMinimumSize(QtCore.QSize(75, 20))
        self.sbDeltaValue1.setMinimum(1.0)
        self.sbDeltaValue1.setMaximum(999.99)
        self.sbDeltaValue1.setSingleStep(0.1)
        self.sbDeltaValue1.setProperty("value", 957.0)
        self.sbDeltaValue1.setObjectName("sbDeltaValue1")
        self.horizontalLayout_9.addWidget(self.sbDeltaValue1)
        self.sbDeltaValue2 = QtWidgets.QDoubleSpinBox(self.gbDeltaSeries)
        self.sbDeltaValue2.setMinimumSize(QtCore.QSize(75, 20))
        self.sbDeltaValue2.setMinimum(1.0)
        self.sbDeltaValue2.setMaximum(999.99)
        self.sbDeltaValue2.setSingleStep(0.1)
        self.sbDeltaValue2.setProperty("value", 162.14)
        self.sbDeltaValue2.setObjectName("sbDeltaValue2")
        self.horizontalLayout_9.addWidget(self.sbDeltaValue2)
        self.gridLayout_9.addLayout(self.horizontalLayout_9, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gbDeltaSeries)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 8, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.sbDeltaRepetition1 = QtWidgets.QSpinBox(self.gbDeltaSeries)
        self.sbDeltaRepetition1.setMinimumSize(QtCore.QSize(75, 20))
        self.sbDeltaRepetition1.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbDeltaRepetition1.setMinimum(-1)
        self.sbDeltaRepetition1.setMaximum(99)
        self.sbDeltaRepetition1.setProperty("value", -1)
        self.sbDeltaRepetition1.setObjectName("sbDeltaRepetition1")
        self.horizontalLayout_12.addWidget(self.sbDeltaRepetition1)
        self.sbDeltaRepetition2 = QtWidgets.QSpinBox(self.gbDeltaSeries)
        self.sbDeltaRepetition2.setMinimumSize(QtCore.QSize(75, 20))
        self.sbDeltaRepetition2.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbDeltaRepetition2.setMinimum(-1)
        self.sbDeltaRepetition2.setMaximum(99)
        self.sbDeltaRepetition2.setProperty("value", -1)
        self.sbDeltaRepetition2.setObjectName("sbDeltaRepetition2")
        self.horizontalLayout_12.addWidget(self.sbDeltaRepetition2)
        self.gridLayout_9.addLayout(self.horizontalLayout_12, 9, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.chDelta1 = QtWidgets.QCheckBox(self.gbDeltaSeries)
        self.chDelta1.setChecked(True)
        self.chDelta1.setObjectName("chDelta1")
        self.horizontalLayout_10.addWidget(self.chDelta1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.chDelta2 = QtWidgets.QCheckBox(self.gbDeltaSeries)
        self.chDelta2.setObjectName("chDelta2")
        self.horizontalLayout_10.addWidget(self.chDelta2)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.gridLayout_9.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem7, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem8, 4, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem9, 7, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem10, 10, 0, 1, 1)
        self.hlCenter.addWidget(self.gbDeltaSeries)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btLoadPeaks = QtWidgets.QToolButton(self.centralwidget)
        self.btLoadPeaks.setIcon(icon)
        self.btLoadPeaks.setIconSize(QtCore.QSize(24, 24))
        self.btLoadPeaks.setAutoRaise(True)
        self.btLoadPeaks.setObjectName("btLoadPeaks")
        self.verticalLayout_4.addWidget(self.btLoadPeaks)
        self.btSaveSpectrum = QtWidgets.QToolButton(self.centralwidget)
        self.btSaveSpectrum.setIcon(icon1)
        self.btSaveSpectrum.setIconSize(QtCore.QSize(24, 24))
        self.btSaveSpectrum.setAutoRaise(True)
        self.btSaveSpectrum.setObjectName("btSaveSpectrum")
        self.verticalLayout_4.addWidget(self.btSaveSpectrum)
        spacerItem11 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.btResetZoom = QtWidgets.QToolButton(self.centralwidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/mofi resource/images/ResetZoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btResetZoom.setIcon(icon9)
        self.btResetZoom.setIconSize(QtCore.QSize(24, 24))
        self.btResetZoom.setAutoRaise(True)
        self.btResetZoom.setObjectName("btResetZoom")
        self.verticalLayout_4.addWidget(self.btResetZoom)
        self.btLabelPeaks = QtWidgets.QToolButton(self.centralwidget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/mofi resource/images/Label.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btLabelPeaks.setIcon(icon10)
        self.btLabelPeaks.setIconSize(QtCore.QSize(24, 24))
        self.btLabelPeaks.setCheckable(True)
        self.btLabelPeaks.setChecked(True)
        self.btLabelPeaks.setAutoRaise(True)
        self.btLabelPeaks.setObjectName("btLabelPeaks")
        self.verticalLayout_4.addWidget(self.btLabelPeaks)
        spacerItem12 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.btModeSelection = QtWidgets.QToolButton(self.centralwidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/mofi resource/images/SelectMode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btModeSelection.setIcon(icon11)
        self.btModeSelection.setIconSize(QtCore.QSize(24, 24))
        self.btModeSelection.setCheckable(True)
        self.btModeSelection.setChecked(True)
        self.btModeSelection.setAutoRaise(True)
        self.btModeSelection.setObjectName("btModeSelection")
        self.verticalLayout_4.addWidget(self.btModeSelection)
        self.btModeDelta = QtWidgets.QToolButton(self.centralwidget)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/mofi resource/images/DeltaMassMode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btModeDelta.setIcon(icon12)
        self.btModeDelta.setIconSize(QtCore.QSize(24, 24))
        self.btModeDelta.setCheckable(True)
        self.btModeDelta.setChecked(False)
        self.btModeDelta.setAutoRaise(True)
        self.btModeDelta.setObjectName("btModeDelta")
        self.verticalLayout_4.addWidget(self.btModeDelta)
        self.hlCenter.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.hlCenter)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.hlStartSearch = QtWidgets.QHBoxLayout()
        self.hlStartSearch.setObjectName("hlStartSearch")
        self.btFindModifications = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btFindModifications.sizePolicy().hasHeightForWidth())
        self.btFindModifications.setSizePolicy(sizePolicy)
        self.btFindModifications.setMinimumSize(QtCore.QSize(120, 25))
        self.btFindModifications.setStyleSheet("QPushButton {\n"
"    border: 1px solid #aa0000;\n"
"    border-radius: 2px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #ffecec, stop: 1 #ffd5d5);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #ffd5d5, stop: 1 #ffecec);\n"
"}")
        self.btFindModifications.setObjectName("btFindModifications")
        self.hlStartSearch.addWidget(self.btFindModifications)
        self.rbAllPeaks = QtWidgets.QRadioButton(self.centralwidget)
        self.rbAllPeaks.setChecked(True)
        self.rbAllPeaks.setObjectName("rbAllPeaks")
        self.hlStartSearch.addWidget(self.rbAllPeaks)
        self.rbSingleMass = QtWidgets.QRadioButton(self.centralwidget)
        self.rbSingleMass.setObjectName("rbSingleMass")
        self.hlStartSearch.addWidget(self.rbSingleMass)
        self.sbSingleMass = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbSingleMass.sizePolicy().hasHeightForWidth())
        self.sbSingleMass.setSizePolicy(sizePolicy)
        self.sbSingleMass.setDecimals(2)
        self.sbSingleMass.setMaximum(500000.0)
        self.sbSingleMass.setSingleStep(0.1)
        self.sbSingleMass.setObjectName("sbSingleMass")
        self.hlStartSearch.addWidget(self.sbSingleMass)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.hlStartSearch.addWidget(self.label_10)
        self.sbTolerance = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbTolerance.sizePolicy().hasHeightForWidth())
        self.sbTolerance.setSizePolicy(sizePolicy)
        self.sbTolerance.setMinimumSize(QtCore.QSize(80, 0))
        self.sbTolerance.setPrefix("")
        self.sbTolerance.setMaximum(50.0)
        self.sbTolerance.setSingleStep(0.1)
        self.sbTolerance.setProperty("value", 5.0)
        self.sbTolerance.setObjectName("sbTolerance")
        self.hlStartSearch.addWidget(self.sbTolerance)
        self.cbTolerance = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTolerance.sizePolicy().hasHeightForWidth())
        self.cbTolerance.setSizePolicy(sizePolicy)
        self.cbTolerance.setObjectName("cbTolerance")
        self.cbTolerance.addItem("")
        self.cbTolerance.addItem("")
        self.hlStartSearch.addWidget(self.cbTolerance)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hlStartSearch.addItem(spacerItem13)
        self.verticalLayout_6.addLayout(self.hlStartSearch)
        self.hlBottom = QtWidgets.QHBoxLayout()
        self.hlBottom.setObjectName("hlBottom")
        self.taResults = QtWidgets.QTabWidget(self.centralwidget)
        self.taResults.setTabPosition(QtWidgets.QTabWidget.East)
        self.taResults.setTabBarAutoHide(False)
        self.taResults.setObjectName("taResults")
        self.stage1Tab = QtWidgets.QWidget()
        self.stage1Tab.setObjectName("stage1Tab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.stage1Tab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.twResults1 = QtWidgets.QTreeWidget(self.stage1Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twResults1.sizePolicy().hasHeightForWidth())
        self.twResults1.setSizePolicy(sizePolicy)
        self.twResults1.setMinimumSize(QtCore.QSize(0, 0))
        self.twResults1.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.twResults1.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twResults1.setUniformRowHeights(True)
        self.twResults1.setColumnCount(0)
        self.twResults1.setObjectName("twResults1")
        self.verticalLayout_12.addWidget(self.twResults1)
        self.taResults.addTab(self.stage1Tab, "")
        self.stage2Tab = QtWidgets.QWidget()
        self.stage2Tab.setObjectName("stage2Tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.stage2Tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.twResults2 = QtWidgets.QTreeWidget(self.stage2Tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twResults2.sizePolicy().hasHeightForWidth())
        self.twResults2.setSizePolicy(sizePolicy)
        self.twResults2.setMinimumSize(QtCore.QSize(0, 0))
        self.twResults2.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.twResults2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twResults2.setUniformRowHeights(True)
        self.twResults2.setColumnCount(0)
        self.twResults2.setObjectName("twResults2")
        self.verticalLayout_9.addWidget(self.twResults2)
        self.taResults.addTab(self.stage2Tab, "")
        self.statisticsTab = QtWidgets.QWidget()
        self.statisticsTab.setObjectName("statisticsTab")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.statisticsTab)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.tbStatistics = QtWidgets.QTableWidget(self.statisticsTab)
        self.tbStatistics.setObjectName("tbStatistics")
        self.tbStatistics.setColumnCount(7)
        self.tbStatistics.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbStatistics.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbStatistics.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbStatistics.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbStatistics.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbStatistics.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbStatistics.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbStatistics.setHorizontalHeaderItem(6, item)
        self.tbStatistics.verticalHeader().setVisible(False)
        self.tbStatistics.verticalHeader().setDefaultSectionSize(22)
        self.tbStatistics.verticalHeader().setMinimumSectionSize(0)
        self.horizontalLayout_16.addWidget(self.tbStatistics)
        self.taResults.addTab(self.statisticsTab, "")
        self.hlBottom.addWidget(self.taResults)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btSaveResults = QtWidgets.QToolButton(self.centralwidget)
        self.btSaveResults.setIcon(icon1)
        self.btSaveResults.setIconSize(QtCore.QSize(24, 24))
        self.btSaveResults.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btSaveResults.setAutoRaise(True)
        self.btSaveResults.setArrowType(QtCore.Qt.NoArrow)
        self.btSaveResults.setObjectName("btSaveResults")
        self.verticalLayout_2.addWidget(self.btSaveResults)
        self.btClearFilters = QtWidgets.QToolButton(self.centralwidget)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/mofi resource/images/ClearFilters.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btClearFilters.setIcon(icon13)
        self.btClearFilters.setIconSize(QtCore.QSize(24, 24))
        self.btClearFilters.setAutoRaise(True)
        self.btClearFilters.setObjectName("btClearFilters")
        self.verticalLayout_2.addWidget(self.btClearFilters)
        self.btCollapseAll = QtWidgets.QToolButton(self.centralwidget)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/mofi resource/images/CollapseAll.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btCollapseAll.setIcon(icon14)
        self.btCollapseAll.setIconSize(QtCore.QSize(24, 24))
        self.btCollapseAll.setAutoRaise(True)
        self.btCollapseAll.setObjectName("btCollapseAll")
        self.verticalLayout_2.addWidget(self.btCollapseAll)
        self.btExpandParents = QtWidgets.QToolButton(self.centralwidget)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/mofi resource/images/Expand1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btExpandParents.setIcon(icon15)
        self.btExpandParents.setIconSize(QtCore.QSize(24, 24))
        self.btExpandParents.setAutoRaise(True)
        self.btExpandParents.setObjectName("btExpandParents")
        self.verticalLayout_2.addWidget(self.btExpandParents)
        self.btExpandAll = QtWidgets.QToolButton(self.centralwidget)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/mofi resource/images/Expand2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btExpandAll.setIcon(icon16)
        self.btExpandAll.setIconSize(QtCore.QSize(24, 24))
        self.btExpandAll.setAutoRaise(True)
        self.btExpandAll.setObjectName("btExpandAll")
        self.verticalLayout_2.addWidget(self.btExpandAll)
        self.btCheckAll = QtWidgets.QToolButton(self.centralwidget)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/mofi resource/images/CheckAll.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btCheckAll.setIcon(icon17)
        self.btCheckAll.setIconSize(QtCore.QSize(24, 24))
        self.btCheckAll.setAutoRaise(True)
        self.btCheckAll.setObjectName("btCheckAll")
        self.verticalLayout_2.addWidget(self.btCheckAll)
        self.btUncheckAll = QtWidgets.QToolButton(self.centralwidget)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/mofi resource/images/UncheckAll.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btUncheckAll.setIcon(icon18)
        self.btUncheckAll.setIconSize(QtCore.QSize(24, 24))
        self.btUncheckAll.setAutoRaise(True)
        self.btUncheckAll.setObjectName("btUncheckAll")
        self.verticalLayout_2.addWidget(self.btUncheckAll)
        self.hlBottom.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.hlBottom)
        self.line_2.raise_()
        self.line_3.raise_()
        ModFinder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ModFinder)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1356, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        ModFinder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ModFinder)
        self.statusbar.setObjectName("statusbar")
        ModFinder.setStatusBar(self.statusbar)
        self.acAbout = QtWidgets.QAction(ModFinder)
        self.acAbout.setObjectName("acAbout")
        self.acLoadSettings = QtWidgets.QAction(ModFinder)
        self.acLoadSettings.setObjectName("acLoadSettings")
        self.acSaveSettings = QtWidgets.QAction(ModFinder)
        self.acSaveSettings.setObjectName("acSaveSettings")
        self.acQuit = QtWidgets.QAction(ModFinder)
        self.acQuit.setObjectName("acQuit")
        self.acManual = QtWidgets.QAction(ModFinder)
        self.acManual.setObjectName("acManual")
        self.acWhatIs = QtWidgets.QAction(ModFinder)
        self.acWhatIs.setObjectName("acWhatIs")
        self.menuFile.addAction(self.acLoadSettings)
        self.menuFile.addAction(self.acSaveSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.acQuit)
        self.menuHelp.addAction(self.acManual)
        self.menuHelp.addAction(self.acWhatIs)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.acAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ModFinder)
        self.taResults.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ModFinder)
        ModFinder.setTabOrder(self.btLoadSequence, self.btSaveSequence)
        ModFinder.setTabOrder(self.btSaveSequence, self.btClearSequence)
        ModFinder.setTabOrder(self.btClearSequence, self.btUpdateMass)
        ModFinder.setTabOrder(self.btUpdateMass, self.teSequence)
        ModFinder.setTabOrder(self.teSequence, self.sbDisulfides)
        ModFinder.setTabOrder(self.sbDisulfides, self.chPngase)
        ModFinder.setTabOrder(self.chPngase, self.cbMassSet)
        ModFinder.setTabOrder(self.cbMassSet, self.btLoadMonomers)
        ModFinder.setTabOrder(self.btLoadMonomers, self.btSaveMonomers)
        ModFinder.setTabOrder(self.btSaveMonomers, self.btDefaultMonomers)
        ModFinder.setTabOrder(self.btDefaultMonomers, self.btInsertRowAboveMonomers)
        ModFinder.setTabOrder(self.btInsertRowAboveMonomers, self.btInsertRowBelowMonomers)
        ModFinder.setTabOrder(self.btInsertRowBelowMonomers, self.btDeleteRowMonomers)
        ModFinder.setTabOrder(self.btDeleteRowMonomers, self.btClearMonomers)
        ModFinder.setTabOrder(self.btClearMonomers, self.tbMonomers)
        ModFinder.setTabOrder(self.tbMonomers, self.btLoadPolymers)
        ModFinder.setTabOrder(self.btLoadPolymers, self.btSavePolymers)
        ModFinder.setTabOrder(self.btSavePolymers, self.btDefaultPolymers)
        ModFinder.setTabOrder(self.btDefaultPolymers, self.btInsertRowAbovePolymers)
        ModFinder.setTabOrder(self.btInsertRowAbovePolymers, self.btInsertRowBelowPolymers)
        ModFinder.setTabOrder(self.btInsertRowBelowPolymers, self.btDeleteRowPolymers)
        ModFinder.setTabOrder(self.btDeleteRowPolymers, self.btClearPolymers)
        ModFinder.setTabOrder(self.btClearPolymers, self.tbPolymers)
        ModFinder.setTabOrder(self.tbPolymers, self.chDelta1)
        ModFinder.setTabOrder(self.chDelta1, self.sbDeltaValue1)
        ModFinder.setTabOrder(self.sbDeltaValue1, self.sbDeltaTolerance1)
        ModFinder.setTabOrder(self.sbDeltaTolerance1, self.sbDeltaRepetition1)
        ModFinder.setTabOrder(self.sbDeltaRepetition1, self.chDelta2)
        ModFinder.setTabOrder(self.chDelta2, self.sbDeltaValue2)
        ModFinder.setTabOrder(self.sbDeltaValue2, self.sbDeltaTolerance2)
        ModFinder.setTabOrder(self.sbDeltaTolerance2, self.sbDeltaRepetition2)
        ModFinder.setTabOrder(self.sbDeltaRepetition2, self.chCombineDelta)
        ModFinder.setTabOrder(self.chCombineDelta, self.btLoadPeaks)
        ModFinder.setTabOrder(self.btLoadPeaks, self.btSaveSpectrum)
        ModFinder.setTabOrder(self.btSaveSpectrum, self.btResetZoom)
        ModFinder.setTabOrder(self.btResetZoom, self.btLabelPeaks)
        ModFinder.setTabOrder(self.btLabelPeaks, self.btModeSelection)
        ModFinder.setTabOrder(self.btModeSelection, self.btModeDelta)
        ModFinder.setTabOrder(self.btModeDelta, self.btFindModifications)
        ModFinder.setTabOrder(self.btFindModifications, self.rbAllPeaks)
        ModFinder.setTabOrder(self.rbAllPeaks, self.rbSingleMass)
        ModFinder.setTabOrder(self.rbSingleMass, self.sbSingleMass)
        ModFinder.setTabOrder(self.sbSingleMass, self.sbTolerance)
        ModFinder.setTabOrder(self.sbTolerance, self.cbTolerance)
        ModFinder.setTabOrder(self.cbTolerance, self.taResults)
        ModFinder.setTabOrder(self.taResults, self.twResults1)
        ModFinder.setTabOrder(self.twResults1, self.twResults2)
        ModFinder.setTabOrder(self.twResults2, self.tbStatistics)
        ModFinder.setTabOrder(self.tbStatistics, self.btSaveResults)
        ModFinder.setTabOrder(self.btSaveResults, self.btClearFilters)
        ModFinder.setTabOrder(self.btClearFilters, self.btCollapseAll)
        ModFinder.setTabOrder(self.btCollapseAll, self.btExpandParents)
        ModFinder.setTabOrder(self.btExpandParents, self.btExpandAll)
        ModFinder.setTabOrder(self.btExpandAll, self.btCheckAll)
        ModFinder.setTabOrder(self.btCheckAll, self.btUncheckAll)

    def retranslateUi(self, ModFinder):
        _translate = QtCore.QCoreApplication.translate
        ModFinder.setWindowTitle(_translate("ModFinder", "ModFinder"))
        self.groupBox.setTitle(_translate("ModFinder", "Sequence"))
        self.btLoadSequence.setToolTip(_translate("ModFinder", "Load sequence"))
        self.btSaveSequence.setToolTip(_translate("ModFinder", "Save sequence"))
        self.btClearSequence.setToolTip(_translate("ModFinder", "Clear sequence"))
        self.btUpdateMass.setToolTip(_translate("ModFinder", "Update masses"))
        self.label_5.setText(_translate("ModFinder", "Disulfides:"))
        self.chPngase.setText(_translate("ModFinder", "PNGase F"))
        self.label_6.setText(_translate("ModFinder", "Mass set:"))
        self.groupBox_2.setTitle(_translate("ModFinder", "Composition"))
        self.btLoadMonomers.setToolTip(_translate("ModFinder", "Load modifications"))
        self.btSaveMonomers.setToolTip(_translate("ModFinder", "Save modifications"))
        self.btDefaultMonomers.setToolTip(_translate("ModFinder", "Load default modifications"))
        self.btInsertRowAboveMonomers.setToolTip(_translate("ModFinder", "Insert row above"))
        self.btInsertRowBelowMonomers.setToolTip(_translate("ModFinder", "Insert row below"))
        self.btDeleteRowMonomers.setToolTip(_translate("ModFinder", "Delete row"))
        self.btClearMonomers.setToolTip(_translate("ModFinder", "Clear table"))
        item = self.tbMonomers.horizontalHeaderItem(0)
        item.setText(_translate("ModFinder", "Use?"))
        item = self.tbMonomers.horizontalHeaderItem(1)
        item.setText(_translate("ModFinder", "Name"))
        item = self.tbMonomers.horizontalHeaderItem(2)
        item.setText(_translate("ModFinder", "Formula"))
        item = self.tbMonomers.horizontalHeaderItem(3)
        item.setText(_translate("ModFinder", "Min"))
        item = self.tbMonomers.horizontalHeaderItem(4)
        item.setText(_translate("ModFinder", "Max"))
        self.groupBox_4.setTitle(_translate("ModFinder", "Structure"))
        self.btLoadPolymers.setToolTip(_translate("ModFinder", "Load glycans"))
        self.btSavePolymers.setToolTip(_translate("ModFinder", "Save glycans"))
        self.btDefaultPolymers.setToolTip(_translate("ModFinder", "Load default glycans"))
        self.btInsertRowAbovePolymers.setToolTip(_translate("ModFinder", "Insert row above"))
        self.btInsertRowBelowPolymers.setToolTip(_translate("ModFinder", "Insert row below"))
        self.btDeleteRowPolymers.setToolTip(_translate("ModFinder", "Delete row"))
        self.btClearPolymers.setToolTip(_translate("ModFinder", "Clear table"))
        item = self.tbPolymers.horizontalHeaderItem(0)
        item.setText(_translate("ModFinder", "Use?"))
        item = self.tbPolymers.horizontalHeaderItem(1)
        item.setText(_translate("ModFinder", "Name"))
        item = self.tbPolymers.horizontalHeaderItem(2)
        item.setText(_translate("ModFinder", "Composition"))
        item = self.tbPolymers.horizontalHeaderItem(3)
        item.setText(_translate("ModFinder", "Sites"))
        item = self.tbPolymers.horizontalHeaderItem(4)
        item.setText(_translate("ModFinder", "Abun."))
        self.gbDeltaSeries.setTitle(_translate("ModFinder", "Delta series"))
        self.chCombineDelta.setText(_translate("ModFinder", "Combine"))
        self.label_3.setText(_translate("ModFinder", "Tolerance (Da):"))
        self.label_7.setText(_translate("ModFinder", "Mass differences (Da):"))
        self.label_11.setText(_translate("ModFinder", "Maximum repetitions:"))
        self.sbDeltaRepetition1.setSpecialValueText(_translate("ModFinder", "auto"))
        self.sbDeltaRepetition2.setSpecialValueText(_translate("ModFinder", "auto"))
        self.chDelta1.setText(_translate("ModFinder", "1"))
        self.chDelta2.setText(_translate("ModFinder", "2"))
        self.btLoadPeaks.setToolTip(_translate("ModFinder", "Load mass list"))
        self.btSaveSpectrum.setToolTip(_translate("ModFinder", "Save spectrum"))
        self.btResetZoom.setToolTip(_translate("ModFinder", "Reset zoom"))
        self.btResetZoom.setText(_translate("ModFinder", "Reset zoom"))
        self.btLabelPeaks.setToolTip(_translate("ModFinder", "Label peaks"))
        self.btLabelPeaks.setText(_translate("ModFinder", "Label peaks"))
        self.btModeSelection.setToolTip(_translate("ModFinder", "Select peaks"))
        self.btModeSelection.setText(_translate("ModFinder", "Select peaks"))
        self.btModeDelta.setToolTip(_translate("ModFinder", "Select delta series"))
        self.btModeDelta.setText(_translate("ModFinder", "Select delta series"))
        self.btFindModifications.setText(_translate("ModFinder", "Find modifications"))
        self.rbAllPeaks.setText(_translate("ModFinder", "for all peaks"))
        self.rbSingleMass.setText(_translate("ModFinder", "for a single mass:"))
        self.label_10.setText(_translate("ModFinder", "with tolerance ±"))
        self.cbTolerance.setItemText(0, _translate("ModFinder", "Da"))
        self.cbTolerance.setItemText(1, _translate("ModFinder", "ppm"))
        self.twResults1.setSortingEnabled(True)
        self.taResults.setTabText(self.taResults.indexOf(self.stage1Tab), _translate("ModFinder", "Composition"))
        self.twResults2.setSortingEnabled(True)
        self.taResults.setTabText(self.taResults.indexOf(self.stage2Tab), _translate("ModFinder", "Structure"))
        self.tbStatistics.setSortingEnabled(True)
        item = self.tbStatistics.horizontalHeaderItem(0)
        item.setText(_translate("ModFinder", "ID"))
        item = self.tbStatistics.horizontalHeaderItem(1)
        item.setText(_translate("ModFinder", "Exp. Mass"))
        item = self.tbStatistics.horizontalHeaderItem(2)
        item.setText(_translate("ModFinder", "%"))
        item = self.tbStatistics.horizontalHeaderItem(3)
        item.setText(_translate("ModFinder", "Search space size"))
        item = self.tbStatistics.horizontalHeaderItem(4)
        item.setText(_translate("ModFinder", "Stage 1 results"))
        item = self.tbStatistics.horizontalHeaderItem(5)
        item.setText(_translate("ModFinder", "Stage 2 permutations"))
        item = self.tbStatistics.horizontalHeaderItem(6)
        item.setText(_translate("ModFinder", "Stage 2 hits"))
        self.taResults.setTabText(self.taResults.indexOf(self.statisticsTab), _translate("ModFinder", "Statistics"))
        self.btSaveResults.setToolTip(_translate("ModFinder", "Save results"))
        self.btSaveResults.setText(_translate("ModFinder", "..."))
        self.btClearFilters.setToolTip(_translate("ModFinder", "Clear filters"))
        self.btCollapseAll.setToolTip(_translate("ModFinder", "Collapse all"))
        self.btExpandParents.setToolTip(_translate("ModFinder", "Expand parent items"))
        self.btExpandAll.setToolTip(_translate("ModFinder", "Expand all"))
        self.btCheckAll.setToolTip(_translate("ModFinder", "Check all"))
        self.btUncheckAll.setToolTip(_translate("ModFinder", "Uncheck all"))
        self.menuFile.setTitle(_translate("ModFinder", "File"))
        self.menuHelp.setTitle(_translate("ModFinder", "Help"))
        self.acAbout.setText(_translate("ModFinder", "About"))
        self.acLoadSettings.setText(_translate("ModFinder", "Load settings ..."))
        self.acLoadSettings.setShortcut(_translate("ModFinder", "Ctrl+O"))
        self.acSaveSettings.setText(_translate("ModFinder", "Save settings ..."))
        self.acSaveSettings.setShortcut(_translate("ModFinder", "Ctrl+S"))
        self.acQuit.setText(_translate("ModFinder", "Quit"))
        self.acQuit.setShortcut(_translate("ModFinder", "Ctrl+Q"))
        self.acManual.setText(_translate("ModFinder", "Manual"))
        self.acWhatIs.setText(_translate("ModFinder", "What is ..."))
        self.acWhatIs.setShortcut(_translate("ModFinder", "Shift+F1"))

from mofi import mofi_rc
